"""
    DSB Client Gateway

    DSB Client Gateway  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.get_messages_response_dto import GetMessagesResponseDto


class TestGetMessagesResponseDto(unittest.TestCase):
    """GetMessagesResponseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetMessagesResponseDto(self):
        """Test GetMessagesResponseDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetMessagesResponseDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
