"""
    DDHub Client Gateway

    DDHub Client Gateway  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import ddhub_gateway_client
from ddhub_gateway_client.api.topics_api import TopicsApi  # noqa: E501


class TestTopicsApi(unittest.TestCase):
    """TopicsApi unit test stubs"""

    def setUp(self):
        self.api = TopicsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_topics_controller_delete_topics(self):
        """Test case for topics_controller_delete_topics

        """
        pass

    def test_topics_controller_delete_topics_by_version(self):
        """Test case for topics_controller_delete_topics_by_version

        """
        pass

    def test_topics_controller_get_topic_history_by_id_and_version(self):
        """Test case for topics_controller_get_topic_history_by_id_and_version

        """
        pass

    def test_topics_controller_get_topics(self):
        """Test case for topics_controller_get_topics

        """
        pass

    def test_topics_controller_get_topics_by_search(self):
        """Test case for topics_controller_get_topics_by_search

        """
        pass

    def test_topics_controller_get_topics_count_by_owner(self):
        """Test case for topics_controller_get_topics_count_by_owner

        """
        pass

    def test_topics_controller_get_topics_history_by_id(self):
        """Test case for topics_controller_get_topics_history_by_id

        """
        pass

    def test_topics_controller_post_topics(self):
        """Test case for topics_controller_post_topics

        """
        pass

    def test_topics_controller_update_topics(self):
        """Test case for topics_controller_update_topics

        """
        pass

    def test_topics_controller_update_topics_by_id_and_version(self):
        """Test case for topics_controller_update_topics_by_id_and_version

        """
        pass


if __name__ == '__main__':
    unittest.main()
