"""
    DSB Client Gateway

    DSB Client Gateway  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.channel_conditions import ChannelConditions
globals()['ChannelConditions'] = ChannelConditions
from openapi_client.model.get_channel_response_dto import GetChannelResponseDto


class TestGetChannelResponseDto(unittest.TestCase):
    """GetChannelResponseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetChannelResponseDto(self):
        """Test GetChannelResponseDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetChannelResponseDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
