"""
    DSB Client Gateway

    DSB Client Gateway  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ddhub_gateway_client
from ddhub_gateway_client.model.role_dto import RoleDto


class TestRoleDto(unittest.TestCase):
    """RoleDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRoleDto(self):
        """Test RoleDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RoleDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
