"""
    DDHub Client Gateway

    DDHub Client Gateway  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ddhub_gateway_client
from ddhub_gateway_client.model.get_topic_dto import GetTopicDto
globals()['GetTopicDto'] = GetTopicDto
from ddhub_gateway_client.model.paginated_response import PaginatedResponse


class TestPaginatedResponse(unittest.TestCase):
    """PaginatedResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaginatedResponse(self):
        """Test PaginatedResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PaginatedResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
