"""
    DDHub Client Gateway

    DDHub Client Gateway  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ddhub_gateway_client
from ddhub_gateway_client.model.get_topic_dto import GetTopicDto


class TestGetTopicDto(unittest.TestCase):
    """GetTopicDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetTopicDto(self):
        """Test GetTopicDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetTopicDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
