"""
    DDHub Client Gateway

    DDHub Client Gateway  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ddhub_gateway_client
from ddhub_gateway_client.model.topic_dto import TopicDto
globals()['TopicDto'] = TopicDto
from ddhub_gateway_client.model.channel_conditions_dto import ChannelConditionsDto


class TestChannelConditionsDto(unittest.TestCase):
    """ChannelConditionsDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testChannelConditionsDto(self):
        """Test ChannelConditionsDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ChannelConditionsDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
