"""
    DSB Client Gateway

    DSB Client Gateway  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.get_channel_qualified_dids_dto import GetChannelQualifiedDidsDto


class TestGetChannelQualifiedDidsDto(unittest.TestCase):
    """GetChannelQualifiedDidsDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetChannelQualifiedDidsDto(self):
        """Test GetChannelQualifiedDidsDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetChannelQualifiedDidsDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
