"""
    DSB Client Gateway

    DSB Client Gateway  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ddhub_gateway_client
from ddhub_gateway_client.model.topics_count_response import TopicsCountResponse


class TestTopicsCountResponse(unittest.TestCase):
    """TopicsCountResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTopicsCountResponse(self):
        """Test TopicsCountResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TopicsCountResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
