"""
    DDHub Client Gateway

    DDHub Client Gateway  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ddhub_gateway_client
from ddhub_gateway_client.model.topic_count_dto import TopicCountDto


class TestTopicCountDto(unittest.TestCase):
    """TopicCountDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTopicCountDto(self):
        """Test TopicCountDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TopicCountDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
