"""
    DDHub Client Gateway

    DDHub Client Gateway  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ddhub_gateway_client
from ddhub_gateway_client.model.details import Details
globals()['Details'] = Details
from ddhub_gateway_client.model.status import Status


class TestStatus(unittest.TestCase):
    """Status unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStatus(self):
        """Test Status"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Status()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
