"""
    DSB Client Gateway

    DSB Client Gateway  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.details import Details


class TestDetails(unittest.TestCase):
    """Details unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDetails(self):
        """Test Details"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Details()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
