"""
    DSB Client Gateway

    DSB Client Gateway  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import ddhub_gateway_client
from ddhub_gateway_client.api.channels_api import ChannelsApi  # noqa: E501


class TestChannelsApi(unittest.TestCase):
    """ChannelsApi unit test stubs"""

    def setUp(self):
        self.api = ChannelsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_channel_controller_create(self):
        """Test case for channel_controller_create

        """
        pass

    def test_channel_controller_delete(self):
        """Test case for channel_controller_delete

        """
        pass

    def test_channel_controller_get(self):
        """Test case for channel_controller_get

        """
        pass

    def test_channel_controller_get_by_type(self):
        """Test case for channel_controller_get_by_type

        """
        pass

    def test_channel_controller_get_qualified_dids(self):
        """Test case for channel_controller_get_qualified_dids

        """
        pass

    def test_channel_controller_refresh_did(self):
        """Test case for channel_controller_refresh_did

        """
        pass

    def test_channel_controller_update(self):
        """Test case for channel_controller_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
