"""
    DSB Client Gateway

    DSB Client Gateway  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.role_dto import RoleDto
globals()['RoleDto'] = RoleDto
from openapi_client.model.enrolment_dto import EnrolmentDto


class TestEnrolmentDto(unittest.TestCase):
    """EnrolmentDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEnrolmentDto(self):
        """Test EnrolmentDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EnrolmentDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
