"""
    DSB Client Gateway

    DSB Client Gateway  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ddhub_gateway_client
from ddhub_gateway_client.model.channel_conditions_dto import ChannelConditionsDto
globals()['ChannelConditionsDto'] = ChannelConditionsDto
from ddhub_gateway_client.model.create_channel_dto import CreateChannelDto


class TestCreateChannelDto(unittest.TestCase):
    """CreateChannelDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateChannelDto(self):
        """Test CreateChannelDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreateChannelDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
