"""
    DDHub Client Gateway

    DDHub Client Gateway  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ddhub_gateway_client
from ddhub_gateway_client.model.get_topic_search_dto import GetTopicSearchDto
globals()['GetTopicSearchDto'] = GetTopicSearchDto
from ddhub_gateway_client.model.paginated_topic_response import PaginatedTopicResponse


class TestPaginatedTopicResponse(unittest.TestCase):
    """PaginatedTopicResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaginatedTopicResponse(self):
        """Test PaginatedTopicResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PaginatedTopicResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
