"""
    DDHub Client Gateway

    DDHub Client Gateway  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ddhub_gateway_client
from ddhub_gateway_client.model.put_topic_dto import PutTopicDto


class TestPutTopicDto(unittest.TestCase):
    """PutTopicDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPutTopicDto(self):
        """Test PutTopicDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PutTopicDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
