"""
    DSB Client Gateway

    DSB Client Gateway  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.update_topic_history_body_dto import UpdateTopicHistoryBodyDto


class TestUpdateTopicHistoryBodyDto(unittest.TestCase):
    """UpdateTopicHistoryBodyDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateTopicHistoryBodyDto(self):
        """Test UpdateTopicHistoryBodyDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UpdateTopicHistoryBodyDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
