"""
    DDHub Client Gateway

    DDHub Client Gateway  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import ddhub_gateway_client
from ddhub_gateway_client.api.gateway_configuration_api import GatewayConfigurationApi  # noqa: E501


class TestGatewayConfigurationApi(unittest.TestCase):
    """GatewayConfigurationApi unit test stubs"""

    def setUp(self):
        self.api = GatewayConfigurationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_certificate_controller_save(self):
        """Test case for certificate_controller_save

        """
        pass

    def test_keys_controller_derive(self):
        """Test case for keys_controller_derive

        """
        pass


if __name__ == '__main__':
    unittest.main()
