"""
    DSB Client Gateway

    DSB Client Gateway  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.identity_api import IdentityApi  # noqa: E501


class TestIdentityApi(unittest.TestCase):
    """IdentityApi unit test stubs"""

    def setUp(self):
        self.api = IdentityApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_identity_controller_get(self):
        """Test case for identity_controller_get

        """
        pass

    def test_identity_controller_get_claims(self):
        """Test case for identity_controller_get_claims

        """
        pass

    def test_identity_controller_post(self):
        """Test case for identity_controller_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
