"""
    DDHub Client Gateway

    DDHub Client Gateway  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ddhub_gateway_client
from ddhub_gateway_client.model.cron_response_dto import CronResponseDto


class TestCronResponseDto(unittest.TestCase):
    """CronResponseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCronResponseDto(self):
        """Test CronResponseDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CronResponseDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
