"""
    DDHub Client Gateway

    DDHub Client Gateway  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ddhub_gateway_client
from ddhub_gateway_client.model.enrolment_dto import EnrolmentDto
globals()['EnrolmentDto'] = EnrolmentDto
from ddhub_gateway_client.model.identity_response_dto import IdentityResponseDto


class TestIdentityResponseDto(unittest.TestCase):
    """IdentityResponseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIdentityResponseDto(self):
        """Test IdentityResponseDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = IdentityResponseDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
