"""
    DSB Client Gateway

    DSB Client Gateway  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.channel_topic import ChannelTopic
globals()['ChannelTopic'] = ChannelTopic
from openapi_client.model.channel_conditions import ChannelConditions


class TestChannelConditions(unittest.TestCase):
    """ChannelConditions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testChannelConditions(self):
        """Test ChannelConditions"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ChannelConditions()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
