"""
    DDHub Client Gateway

    DDHub Client Gateway  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import ddhub_gateway_client
from ddhub_gateway_client.api.gateway_api import GatewayApi
from ddhub_gateway_client.model.gateway_response_dto import GatewayResponseDto  # noqa: E501


class TestGatewayApi(unittest.TestCase):
    """GatewayApi unit test stubs"""
    configuration = ddhub_gateway_client.Configuration(
        host = "https://ddhub-gateway-dev.energyweb.org"
    )

    def setUp(self):
        self.api_client = ddhub_gateway_client.ApiClient(self.configuration)
        self.api_instance =  GatewayApi(self.api_client)

    def tearDown(self):
        self.api_client.close()

    def test_gateway_controller_get(self):
        """Test case for gateway_controller_get

        """
        api_response_body, api_response_status, api_response_headers = \
            self.api_instance.gateway_controller_get(
                _return_http_data_only=False
            )
        
        self.assertEqual(200,api_response_status)

        self.assertIsInstance(api_response_body, GatewayResponseDto)


if __name__ == '__main__':
    unittest.main()
