"""
    DDHub Client Gateway

    DDHub Client Gateway  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import ddhub_gateway_client
from ddhub_gateway_client.api.gateway_api import GatewayApi  # noqa: E501


class TestGatewayApi(unittest.TestCase):
    """GatewayApi unit test stubs"""

    def setUp(self):
        self.api = GatewayApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_gateway_controller_get(self):
        """Test case for gateway_controller_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
