"""
    DSB Client Gateway

    DSB Client Gateway  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import ddhub_gateway_client
from ddhub_gateway_client.api.enrolment_api import EnrolmentApi  # noqa: E501


class TestEnrolmentApi(unittest.TestCase):
    """EnrolmentApi unit test stubs"""

    def setUp(self):
        self.api = EnrolmentApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_enrolment_controller_get(self):
        """Test case for enrolment_controller_get

        """
        pass

    def test_enrolment_controller_init(self):
        """Test case for enrolment_controller_init

        """
        pass


if __name__ == '__main__':
    unittest.main()
