"""
    DDHub Client Gateway

    DDHub Client Gateway  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ddhub_gateway_client
from ddhub_gateway_client.model.post_topic_body_dto import PostTopicBodyDto


class TestPostTopicBodyDto(unittest.TestCase):
    """PostTopicBodyDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPostTopicBodyDto(self):
        """Test PostTopicBodyDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PostTopicBodyDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
