"""
    DSB Client Gateway

    DSB Client Gateway  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.create_identity_dto import CreateIdentityDto


class TestCreateIdentityDto(unittest.TestCase):
    """CreateIdentityDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateIdentityDto(self):
        """Test CreateIdentityDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreateIdentityDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
