"""
    DSB Client Gateway

    DSB Client Gateway  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.post_topic_dto import PostTopicDto


class TestPostTopicDto(unittest.TestCase):
    """PostTopicDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPostTopicDto(self):
        """Test PostTopicDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PostTopicDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
