"""
    DSB Client Gateway

    DSB Client Gateway  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.get_topic_search_dto import GetTopicSearchDto
globals()['GetTopicSearchDto'] = GetTopicSearchDto
from openapi_client.model.paginated_search_topic_response import PaginatedSearchTopicResponse


class TestPaginatedSearchTopicResponse(unittest.TestCase):
    """PaginatedSearchTopicResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaginatedSearchTopicResponse(self):
        """Test PaginatedSearchTopicResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PaginatedSearchTopicResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
