"""
    DSB Client Gateway

    DSB Client Gateway  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ddhub_gateway_client
from ddhub_gateway_client.model.get_topic_search_dto import GetTopicSearchDto


class TestGetTopicSearchDto(unittest.TestCase):
    """GetTopicSearchDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetTopicSearchDto(self):
        """Test GetTopicSearchDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetTopicSearchDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
