"""
    DDHub Client Gateway

    DDHub Client Gateway  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ddhub_gateway_client
from ddhub_gateway_client.model.update_topic_body_dto import UpdateTopicBodyDto


class TestUpdateTopicBodyDto(unittest.TestCase):
    """UpdateTopicBodyDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass
    
    def testUpdateTopicBodyDto_invalid(self):
        """Test UpdateTopicBodyDto"""
        with self.assertRaises(TypeError):
            model = UpdateTopicBodyDto("test_tag")

    def testUpdateTopicBodyDto(self):
        """Test UpdateTopicBodyDto"""
        tags=['test_tag']
        model = UpdateTopicBodyDto(tags=tags)
        self.assertIsNotNone(model)
        self.assertListEqual(model.tags, tags)


if __name__ == '__main__':
    unittest.main()
