"""
    DDHub Client Gateway

    DDHub Client Gateway  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import json
import sys
import unittest

import ddhub_gateway_client
from ddhub_gateway_client.model.update_topic_history_body_dto import UpdateTopicHistoryBodyDto


class TestUpdateTopicHistoryBodyDto(unittest.TestCase):
    """UpdateTopicHistoryBodyDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateTopicHistoryBodyDto_invalid_type_param(self):
        """Test UpdateTopicHistoryBodyDto with invalid schema"""
        schema={}
        with self.assertRaises(TypeError):
            model = UpdateTopicHistoryBodyDto(schema=schema)


    def testUpdateTopicHistoryBodyDto(self):
        """Test UpdateTopicHistoryBodyDto"""
        schema = json.dumps({
            "type":"object",
            "properties":{
                "data":{
                    "type":"number"
                },
            },
        })
        model = UpdateTopicHistoryBodyDto(schema)

        self.assertIsNotNone(model)
        self.assertEqual(model.schema, schema)


if __name__ == '__main__':
    unittest.main()
