"""
    DDHub Client Gateway

    DDHub Client Gateway  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import json
import sys
import unittest

import ddhub_gateway_client
from ddhub_gateway_client.model.send_message_dto import SendMessageDto


class TestSendMessageDto(unittest.TestCase):
    """SendMessageDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def test_send_message_dto(self):
        """Test SendMessageDto"""
        fqcn="test.pub.channel"
        topic_name="Topic_JSON_LIB_V1"
        topic_version="1.0.0"
        topic_owner="libtesting.apps.aresguerre.iam.ewc"
        payload=json.dumps({'data': 42})
        model = SendMessageDto(
            fqcn=fqcn,
            topic_name=topic_name,
            topic_version=topic_version,
            topic_owner=topic_owner,
            transaction_id="112233445566",
            payload=payload
        )


if __name__ == '__main__':
    unittest.main()
