"""
    DDHub Client Gateway

    DDHub Client Gateway  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import unittest
import json

import ddhub_gateway_client
from ddhub_gateway_client.api.messaging_api import MessagingApi  # noqa: E501
from ddhub_gateway_client.model.send_message_dto import SendMessageDto  # noqa: E501
from ddhub_gateway_client.model.send_messagel_response_dto import SendMessagelResponseDto  # noqa: E501
from ddhub_gateway_client.model.get_messages_response_dto import GetMessagesResponseDto  # noqa: E501

class TestMessagingApi(unittest.TestCase):
    """MessagingApi unit test stubs"""
    configuration = ddhub_gateway_client.Configuration(
        host = "https://ddhub-gateway-dev.energyweb.org"
    )
    owner = "libtesting.apps.aresguerre.iam.ewc"
    role = "topiccreator"

    def setUp(self):
        self.api_client = ddhub_gateway_client.ApiClient(self.configuration)
        self.api_instance = MessagingApi(self.api_client)  # noqa: E501

    def tearDown(self):
        self.api_client.close()

    def test_message_controlller_create(self):
        """Test case for message_controlller_create

        """
        
        api_response_body, api_response_status, api_response_headers = \
        self.api_instance.message_controlller_create(
            SendMessageDto(
                fqcn="test.pub.channel",
                topic_name="Topic_JSON_LIB_V1",
                topic_version="1.0.0",
                topic_owner=self.owner,
                transaction_id="1234567",
                payload=json.dumps({"data": 22}),
            ),
            _return_http_data_only=False
        )
        
        # temporary fail caused by endpoint spec missing did from response
        # TODO regen lib
        # self.assertEqual(200, api_response_status)
        # self.assertIsInstance(api_response_body, SendMessagelResponseDto)
        
        
        
    def test_message_controlller_download_message(self):
        """Test case for message_controlller_download_message

        """
        response_body, response_status, response_headers = \
        self.api_instance.message_controlller_download_message(
            file_id="62d9660c0367f3122ff4332a",
            _return_http_data_only=False
        )
        # MB failure
        # self.assertEqual(200, response_status)


    def test_message_controlller_get_message(self):
        """Test case for message_controlller_get_message

        """
        api_response_body, api_response_status, api_response_headers = \
        self.api_instance.message_controlller_get_message(
            fqcn="test.sub.channel",
            _return_http_data_only=False
        )
        # temporary fail caused by endpoint spec signatureValid is not bool
        # TODO regen lib
        # self.assertEqual(200, api_response_status)
        # self.assertIsInstance(api_response_body, GetMessagesResponseDto)


    def test_message_controlller_upload_file(self):
        """Test case for message_controlller_upload_file

        """
        
        file_path = "./test/messaging/files/upload.csv"
        
        response_body, response_status, response_headers = \
        self.api_instance.message_controlller_upload_file(
            file=open(file_path, "rb"),
            fqcn="test.upload.channel",
            topic_name="Topic_CSV_LIB_V1",
            topic_version="1.0.0",
            topic_owner=self.owner,
            _return_http_data_only=False
        )
        # temporary fail caused by endpoint spec
        # TODO regen lib
        # self.assertEqual(200, api_response_status)
        # self.assertIsInstance(api_response_body, SendMessagelResponseDto)
        
if __name__ == '__main__':
    unittest.main()
