"""
    DDHub Client Gateway

    DDHub Client Gateway  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import os
import unittest

from py_dotenv import read_dotenv

import ddhub_gateway_client
from ddhub_gateway_client.api.enrolment_api import EnrolmentApi
from ddhub_gateway_client.model.create_identity_dto import CreateIdentityDto  # noqa: E501


env_path =  os.path.join(os.path.abspath('./'), '.env')
if os.path.exists(env_path):
    dotenv_path = os.path.join(os.path.abspath('./'), '.env')
    read_dotenv(dotenv_path)

class TestEnrolmentApi(unittest.TestCase):
    """EnrolmentApi unit test stubs"""
    configuration = ddhub_gateway_client.Configuration(
        host = "https://ddhub-gateway-dev.energyweb.org"
    )

    def setUp(self):
        self.api_client = ddhub_gateway_client.ApiClient(self.configuration)
        self.api_instance = EnrolmentApi(self.api_client)  # noqa: E501

    def tearDown(self):
        self.api_client.close()

    def test_enrolment_controller_get(self):
        """Test case for enrolment_controller_get

        """
        api_response_body, api_response_status, api_response_headers = \
            self.api_instance.enrolment_controller_get(
                _return_http_data_only=False
            )

        self.assertEqual(200,api_response_status)

        # temporary fail caused by endpoint spec
        # TODO regen lib
        # self.assertIsInstance(api_response_body, dict)
        
        # self.assertNotEqual(None, api_response_body.get("roles"))

    def test_enrolment_controller_init(self):
        """Test case for enrolment_controller_init

        """
        pass
        # temporary fail caused by endpoint spec
        # TODO regen lib
        # private_key:str = os.getenv("PRIVATE_KEY")

        # createIdentityDto = CreateIdentityDto()
        # self.api_instance.identity_controller_post(createIdentityDto)

        # api_response_body, api_response_status, api_response_headers = \
        #     self.api_instance.enrolment_controller_init()
        
        # self.assertEqual(200, api_response_status)

        # self.assertIsInstance(api_response_body, dict)

        # api_response = self.api_instance.enrolment_controller_get()
        # roles = list(filter(lambda roles: roles['namespace'] == 'user.roles.ddhub.apps.energyweb.iam.ewc', api_response.enrolment.roles))
        
        # self.assertNotEqual(roles[0], None)

        # createOldIdentityDto = CreateIdentityDto(private_key=private_key)
        # self.api_instance.identity_controller_post(createOldIdentityDto)


if __name__ == '__main__':
    unittest.main()
