"""
    DDHub Client Gateway

    DDHub Client Gateway  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""

import unittest

import ddhub_gateway_client
from ddhub_gateway_client.model.topic_dto import TopicDto
from ddhub_gateway_client.model.channel_conditions_dto import ChannelConditionsDto


class TestChannelConditionsDto(unittest.TestCase):
    """ChannelConditionsDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testChannelConditionsDto(self):
        """Test ChannelConditionsDto"""
        topic_dto = TopicDto(
            topic_name="Topic_JSON_test_py",
            owner="testing01.apps.aemotest.iam.ewc",
        )
        dids = ["did:ethr:volta:0x09Df5d33f1242E1b8aA5E0E0F6BfA687E6846993"]
        roles = ["user.roles.ddhub.apps.energyweb.iam.ewc"]
        topics = [topic_dto]
        model = ChannelConditionsDto(
            dids=dids,
            roles= roles,
            topics= topics)


if __name__ == '__main__':
    unittest.main()
