"""
    DDHub Client Gateway

    DDHub Client Gateway  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ddhub_gateway_client
from ddhub_gateway_client.model.channel_conditions_dto import ChannelConditionsDto
globals()['ChannelConditionsDto'] = ChannelConditionsDto
from ddhub_gateway_client.model.update_channel_dto import UpdateChannelDto


class TestUpdateChannelDto(unittest.TestCase):
    """UpdateChannelDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateChannelDto(self):
        """Test UpdateChannelDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UpdateChannelDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
