"""
    DDHub Client Gateway

    DDHub Client Gateway  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import ddhub_gateway_client
from ddhub_gateway_client.api.identity_api import IdentityApi
from ddhub_gateway_client.model.identity_response_dto import IdentityResponseDto  # noqa: E501


class TestIdentityApi(unittest.TestCase):
    """IdentityApi unit test stubs"""
    configuration = ddhub_gateway_client.Configuration(
        host = "https://ddhub-gateway-dev.energyweb.org"
    )

    def setUp(self):
        self.api_client = ddhub_gateway_client.ApiClient(self.configuration)
        self.api_instance =  IdentityApi(self.api_client)

    def tearDown(self):
        self.api_client.close()

    def test_identity_controller_get(self):
        """Test case for identity_controller_get

        """
        api_response_body, api_response_status, api_response_headers = \
            self.api_instance.identity_controller_get(
                _return_http_data_only=False
            )

        self.assertEqual(200,api_response_status)

        self.assertIsInstance(api_response_body, IdentityResponseDto)

    def test_identity_controller_get_claims(self):
        """Test case for identity_controller_get_claims

        """
        api_response_body, api_response_status, api_response_headers = \
            self.api_instance.identity_controller_get_claims(
                _return_http_data_only=False
            )

        self.assertEqual(200,api_response_status)
        
        self.assertIsInstance(api_response_body, dict)
        
        self.assertNotEqual(None, api_response_body.get("claims"))

    def test_identity_controller_post(self):
        """Test case for identity_controller_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
