"""
    DDHub Client Gateway

    DDHub Client Gateway  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ddhub_gateway_client
from ddhub_gateway_client.model.create_identity_dto import CreateIdentityDto


class TestCreateIdentityDto(unittest.TestCase):
    """CreateIdentityDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateIdentityDto(self):
        """Test CreateIdentityDto"""
        model = CreateIdentityDto()

        pk = "0x38c54494ca8b4c1d235af7936aff04e2f27d4807f690ca1effb169073ec2635a"
        model_pk = CreateIdentityDto(private_key = pk)


if __name__ == '__main__':
    unittest.main()
